### ISSUE TITLE
Incorrect/missing additional notes

### ISSUE THREAD

**Issue by MatthijsBurgh** [motine/cppstylelineup#6]
GNU and Microsoft have the LLVM additonal notes.

Mozilla and Webkit don't have any additional notes.

**Comment by motine** [comment]
hey @MatthijsBurgh, thanks for submitting this issue. would you like to create a pull request for the fix?

**Comment by MatthijsBurgh** [comment]
I am looking for that short summary, as I don't have the knowledge. So I am not the guy for it.

**Comment by motine** [comment]
cool. I thought you had something specific in mind. I am not sure if there is thing "additional" to note for Mozilla & Webkit. If you do not know of anything, I am not sure what to put there. do you have any ideas?

**Comment by aaronliu0130** [comment]
Maybe remove the LLVM notes from GNU and MS first?
