### ISSUE TITLE
GNU.cpp semicolon on line 31

### ISSUE THREAD

**Issue by bmelanman** [motine/cppstylelineup#8]
A semicolon is required after the closing bracket on line 31 of GNU.cpp :)

**Comment by motine** [comment]
hey @bmelanman, thanks for pointing this out. would you mind making a pull request for it?

**Comment by bmelanman** [comment]
Just tried my first pull request! Hope I got everything correct 👍

**Comment by motine** [comment]
i was hoping you would say something like this. i am very happy you tried and succeeded. good work.

let’s continue the discussion in the merge request.
